# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/user/login
Content-Type: application/json

{
   "account" : "a",
   "password" : "123"
}

###

POST http://localhost:8080/user/add
Content-Type: application/json

{
  "account": "a",
  "password": "1",
  "username": "a",
  "phone": "1",
  "mobile": "1",
  "postal_code": "123",
  "address": "aaaaa",
  "email": "dfsf"
}

###

GET http://localhost:8080/user/list
Accept: application/json

###

POST http://localhost:8080/category/getSubCategory/상의(남)
Accept: application/json

###

POST http://localhost:8080/category/getSubCategory
Content-Type: application/json

{
   "main_category" : "상의(남)"

}

###

GET http://localhost:8080/product/getlist/1
Accept: application/json

###

GET http://localhost:8080/product/getBestList
Accept: application/json

###

GET http://localhost:8080/product/findById/2
Accept: application/json

###

GET http://localhost:8080/review/getReview/5
Accept: application/json

###

GET http://localhost:8080/order/findById/1
Accept: application/json

###

POST http://localhost:8080/order/addOrder
Content-Type: application/json

{
   "user_id" : 1,
  "product_id" : 2,
  "count" : 2,
  "all_total": 33820
}

###


DELETE http://localhost:8080/cart/delete/2
Accept: application/json

###

PUT http://localhost:8080/cart/updateIsOrder/1
Content-Type: application/json

###

GET http://localhost:8080/user/findByAccount/1
Accept: application/json

###

GET http://localhost:8080/user/getPoint/1
Accept: application/json

###

PUT http://localhost:8080/cart/updateCount
Content-Type: application/json

{
  "id" : 1,
  "count" : 2
}

###